version: 0.2

phases:
  install:
    commands:
        - apt update -y
        - apt install python3-pip -y
        - apt install build-essential python3-pip libffi-dev python3-dev python3-setuptools libssl-dev
        - mkdir flask_dir && cd flask_dir
        - python3 -m venv venv
        - source venv/bin/activate
        - pip3 install flask
        - flask --version

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
